export const INDICES = [
  { symbol: '^NSEI', name: 'NIFTY 50' },
  { symbol: '^NSEBANK', name: 'Bank Nifty' },
  { symbol: '^BSESN', name: 'Sensex' },
]

export const NIFTY50_SYMBOLS = [
  'ADANIPORTS', 'ADANIENT', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK',
  'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BHARTIARTL', 'BPCL',
  'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY',
  'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE',
  'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK',
  'INFY', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'LT',
  'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC',
  'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SHREECEM',
  'SUNPHARMA', 'TATAMOTORS', 'TATASTEEL', 'TCS', 'TECHM',
  'TITAN', 'TRENT', 'ULTRACEMCO', 'UPL', 'WIPRO',
].map(s => `${s}.NS`)

export const SCREENER_STOCKS = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy', cap: 'large' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT', cap: 'large' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT', cap: 'large' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking', cap: 'large' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking', cap: 'large' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom', cap: 'large' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking', cap: 'large' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG', cap: 'large' },
  { symbol: 'ITC', name: 'ITC', sector: 'FMCG', cap: 'large' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking', cap: 'large' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Infrastructure', cap: 'large' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking', cap: 'large' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Paints', cap: 'large' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto', cap: 'large' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Retail', cap: 'large' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical', sector: 'Pharma', cap: 'large' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Finance', cap: 'large' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG', cap: 'large' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT', cap: 'large' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT', cap: 'large' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto', cap: 'large' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ', sector: 'Infrastructure', cap: 'large' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals', cap: 'large' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals', cap: 'large' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals', cap: 'large' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Auto', cap: 'large' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto', cap: 'large' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto', cap: 'large' },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Energy', cap: 'large' },
  { symbol: 'ONGC', name: 'ONGC', sector: 'Energy', cap: 'large' },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Energy', cap: 'large' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining', cap: 'large' },
  { symbol: 'BPCL', name: 'BPCL', sector: 'Energy', cap: 'large' },
  { symbol: 'DRREDDY', name: "Dr. Reddy's Labs", sector: 'Pharma', cap: 'large' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma', cap: 'large' },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories", sector: 'Pharma', cap: 'large' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare', cap: 'large' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT', cap: 'large' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking', cap: 'large' },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Diversified', cap: 'large' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement', cap: 'large' },
  { symbol: 'SHREECEM', name: 'Shree Cement', sector: 'Cement', cap: 'large' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries', sector: 'FMCG', cap: 'large' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Diversified', cap: 'large' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Finance', cap: 'large' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Insurance', cap: 'large' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance', cap: 'large' },
  { symbol: 'TRENT', name: 'Trent', sector: 'Retail', cap: 'mid' },
  { symbol: 'ZOMATO', name: 'Zomato', sector: 'Food Tech', cap: 'mid' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries', sector: 'Chemicals', cap: 'mid' },
  { symbol: 'HAVELLS', name: 'Havells India', sector: 'Electricals', cap: 'mid' },
  { symbol: 'DABUR', name: 'Dabur India', sector: 'FMCG', cap: 'mid' },
  { symbol: 'MARICO', name: 'Marico', sector: 'FMCG', cap: 'mid' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive', sector: 'FMCG', cap: 'mid' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints', sector: 'Paints', cap: 'mid' },
  { symbol: 'IRCTC', name: 'IRCTC', sector: 'Travel', cap: 'mid' },
  { symbol: 'DMART', name: 'Avenue Supermarts', sector: 'Retail', cap: 'large' },
].map(s => ({ ...s, symbolNS: `${s.symbol}.NS` }))
